name: Run Script Periodically

# Trigger the workflow based on a schedule (every minute in this example)
on:
  schedule:
    - cron: "5 4 * * *"  # Adjust the timing here if needed
  workflow_dispatch: # Allows you to trigger manually if required

jobs:
  run-script:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you need

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run the Script
      - name: Execute Script
        run: node simpelbot.js
